### ISSUE TITLE
Minimal console messages

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-dotnet#1]
**Expected behavior**
When gauge specs are run, the messages on the console can be minimum

**Actual behavior**
Apart from the statistics and the run information, the following is also getting printed
```
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 16.95 ms for <projpath>\testFolder\dotnet\dotnet.csproj.
  dotnet -> <projpath>\testFolder\dotnet\bin\Release\netstandard2.0\dotnet.dll
  dotnet -> <projpath>\testFolder\dotnet\gauge-bin\
```
**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
dotnet (0.0.1.nightly-2018-02-05)
```

**Comment by sriv** [comment]
Cannot seem to get rid of this:

```
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
```

from the `dotnet` cli.

I added a `-q` flag to suppress the project logs. These can be enabled when using `DEBUG` log level.

Fix should be available in nightly >= 12/02/18
