### ISSUE TITLE
Add support for specifying build configuration

### ISSUE THREAD

**Issue by heshamamin** [getgauge/gauge-dotnet#11]
Currently gauge builds the project using "release" configuration. It would be great if the required build configuration could be specified using **GAUGE_CSHARP_PROJECT_CONFIG** setting. Same as https://github.com/getgauge/gauge-csharp

**Comment by nehashri** [comment]
This card still need QA testing.

**Comment by BugDiver** [comment]
The defect in this feature is being tracked as #14
