### ISSUE TITLE
Unable to debug the project in vscode as dlls are getting blocked by some other process instantiated by vscode extension

### ISSUE THREAD

**Issue by preetipadalia** [getgauge/gauge-dotnet#114]
Hi,

I am unable to debug the project because the dlls are getting blocked by some other process initiated by vscode extension. When i kill the process i can debug the code but then intellisense stop working.

PFB the error:
error MSB3021: Unable to copy file "C:\Users\user.nuget\packages\fluentassertions\4.19.4\lib\netstandard1.3\FluentAssertions.Core.dll" to "Sample\gauge_bin\FluentAssertions.Core.dll". The process cannot access the file 'Sample\gauge_bin\FluentAssertions.Core.dll' because it is being used by another process. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3027: Could not copy "obj\Debug\netcoreapp3.1\win-x64\netcore-template.dll" to "Sample\gauge_bin\netcore-template.dll". Exceeded r
etry count of 10. Failed. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3021: Unable to copy file "obj\Debug\netcoreapp3.1\win-x64\netcore-template.dll" to "Sample\gauge_bin\netcore-template.dll". The process cannot access the file 'Sample\gauge_bin\netcore-template.dll' because it is being used by another process. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3027: Could not copy "C:\Users\user.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "Sample\gauge_bin\Gauge.CSharp.Lib.dll". Exceeded retry count of 10. Failed. [Sample\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): error MSB3021: Unable to copy file "C:\Users\user.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "Sample\gauge_bin\Gauge.CSharp.Lib.dll". The process cannot access the file 'Sample\gauge_bin\Gauge.CSharp.Lib.dll' because it is being used by another process. [Sample\netcore-template.csproj]
{"logLevel":"fatal","message":"Unable to build Project in Sample\ndotnet Project build failed.\nRan 'dotnet publish --runtime=win-x64 --configuration=Debug --output="Sample\gauge_bin" "netcore-template.csproj" --verbosit
y=quiet'\n at Gauge.Dotnet.GaugeProjectBuilder.BuildTargetGaugeProject()\r\n at Gauge.Dotnet.StartCommand.TryBuild()"}

Gauge version: 1.1.3
Commit Hash: 9d3a3d5

Plugins
-------
dotnet (0.1.7)
html-report (4.0.8)
screenshot (0.0.1)

**Comment by preetipadalia** [comment]
I am getting the same option for Run Scenario also.

**Comment by sriv** [comment]
I was finally able to get hold of a windows box, and can see this issue for both run and debug.

This happens because the test project assemblies are loaded into a custom load context, which locks the files loaded. Run/Debug launch independent processes and these processes are not able to access the files locked by the original process spawned to help the LanguageServer.

Will raise a PR with a fix.

**Comment by preetipadalia** [comment]
@sriv I see this is closed. Is it available to test?

**Comment by sriv** [comment]
yes, please update your gauge-dotnet plugin to [0.1.8](https://github.com/getgauge/gauge-dotnet/releases/tag/v0.1.8) and try. 1

**Comment by preetipadalia** [comment]
I can still see this issue.
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): warning MSB3026: Could not copy "obj\Debug\netstandard2.0\win-x64\netcore-template.dll" to "c:\Learning\GaugeTesting\gauge_bin\netcore-template.dll". B
eginning retry 2 in 1000ms. The process cannot access the file 'c:\Learning\GaugeTesting\gauge_bin\netcore-template.dll' because it is being used by another process.  [c:\Learning\GaugeTesting\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): warning MSB3026: Could not copy "C:\Users\e3005457\.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "c:\Learning\Gaug
eTesting\gauge_bin\Gauge.CSharp.Lib.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'c:\Learning\GaugeTesting\gauge_bin\Gauge.CSharp.Lib.dll' because it is being used by another process.  [c:\Learning\GaugeTesting\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): warning MSB3026: Could not copy "C:\Users\e3005457\.nuget\packages\fluentassertions\4.19.4\lib\netstandard1.3\FluentAssertions.Core.dll" to "c:\Learnin
g\GaugeTesting\gauge_bin\FluentAssertions.Core.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'c:\Learning\GaugeTesting\gauge_bin\FluentAssertions.Core.dll' because it is being used by another process.  [c:\Learning\GaugeTesting\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): warning MSB3026: Could not copy "C:\Users\e3005457\.nuget\packages\fluentassertions\4.19.4\lib\netstandard1.3\FluentAssertions.dll" to "c:\Learning\Gau
geTesting\gauge_bin\FluentAssertions.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'c:\Learning\GaugeTesting\gauge_bin\FluentAssertions.dll' because it is being used by another process.  [c:\Learning\GaugeTesting\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): warning MSB3026: Could not copy "C:\Users\e3005457\.nuget\packages\gauge.csharp.lib\0.7.6\lib\netstandard2.0\Gauge.CSharp.Lib.dll" to "c:\Learning\Gaug
eTesting\gauge_bin\Gauge.CSharp.Lib.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'c:\Learning\GaugeTesting\gauge_bin\Gauge.CSharp.Lib.dll' because it is being used by another process.  [c:\Learning\GaugeTesting\netcore-template.csproj]
C:\Program Files\dotnet\sdk\3.1.302\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(147,5): warning MSB3026: Could not copy "obj\Debug\netstandard2.0\win-x64\netcore-template.dll" to "c:\Learning\GaugeTesting\gauge_bin\netcore-template.dll". B
eginning retry 3 in 1000ms. The process cannot access the file 'c:\Learning\GaugeTesting\gauge_bin\netcore-template.dll' because it is being used by another process.  [c:\Learning\GaugeTesting\netcore-template.csproj]


Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
dotnet (0.1.8)
html-report (4.0.8)
screenshot (0.0.1)

**Comment by sriv** [comment]
When do you see this?

**Comment by preetipadalia** [comment]
When I click on Debug/Run Scenario. When it is trying to publish the project to gauge_bin.

**Comment by preetipadalia** [comment]
can we please open this again as the issue still not fixed.

**Comment by sriv** [comment]
Strange, can you try in a new project (ensure that old gauge processes are not running, i.e. close existing editors, perhaps even reboot your machine)

Here's what happens on my Windows VM:

![gauge-dotnet-debug_win](https://user-images.githubusercontent.com/389148/93086438-c2be0280-f6b4-11ea-95b7-5cafcc3e8127.gif)

**Comment by sriv** [comment]
Don't mind reopening, but would need help in replicating this.

**Comment by preetipadalia** [comment]
I am sharing my system environment details. Can you please share yours so that I can verify by replicating your environment.

Following is my working environment detail:
gauge extension version : 0.0.15
dotnet version: 3.1.302

gauge versions:
Gauge version: 1.1.4
Commit Hash: c982558

Plugins
-------
dotnet (0.1.8)
html-report (4.0.8)
screenshot (0.0.1)

**Comment by preetipadalia** [comment]
Hi @sriv,

Following are few findings which I have experienced.

1. Sometimes debugging is working and sometimes it's not.
2. When debugging is not working I Can see there are two dotnet processes available in the taskbar while in the other case only 1 dotnet process would be there.
2. In the Sample project with target framework netstandard 2.0 breakpoints are working, but if I change it to netcoreapp3.1 the breakpoints are showing as disabled.
3. I am using extent report for my project and it is not working with this update.

Thanks
Preeti

**Comment by sriv** [comment]
Thanks for sharing the points @preetipadalia , appreciate it.

Could you try something: Add `GAUGE_IGNORE_RUNNER_BUILD_FAILURES = true` in your `env/default/default.properties` and if that helps you run/debug?

**Comment by preetipadalia** [comment]
Getting following error with this setting:

  failed to initialize suite datastore. Error: Object reference not set to an instance of an object.

**Comment by preetipadalia** [comment]
@sriv I just found this:
https://github.com/getgauge/gauge-dotnet/issues/80

how can set runtime in publish command. Can you please tell me what value i need to set in properties file.

**Comment by preetipadalia** [comment]
I am not able to take this build but if there is any workaround for SQLData client platform not supported issue can you please explain. That would be very much helpful.

**Comment by preetipadalia** [comment]
@sriv any update on this issue?

**Comment by sriv** [comment]
no, not yet. will post when I figure out more.

**Comment by sriv** [comment]
@preetipadalia can you try now with gauge-dotnet 0.1.9?

**Comment by preetipadalia** [comment]
@sriv finally I am not getting the process is being used error.  Thanks a lot for solving the issue.

I am getting exception while flushing the extent reports in the new releases of the gauge. Should I raise a new JI for this?
