### ISSUE TITLE
GAUGE_CSHARP_PROJECT_CONFIG setting should be honored on Mac as well

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-dotnet#14]
**Actual behavior**
It does not work as expected on OSx

**Steps to replicate**
* Create a new dotnet project `gauge init dotnet`
> This creates a new project with GAUGE_CSHARP_PROJECT_CONFIG set to `release`
* Run the specs `gauge run specs`
> The obj and the bin folder have `Debug` and `release` artifacts

**Version**
> OS - MacOS High Sierra
```
Gauge version: 1.0.1.nightly-2018-07-09
Commit Hash: 72109fa

Plugins
-------
dotnet (0.0.2.nightly-2018-07-05)
```
Blocks #11

**Comment by BugDiver** [comment]
@sguptatw  I'm not able to see the `Debug` artifacts when I run the project in `release` mode.
Can you try the same steps in and empty dir?

**Comment by sguptatw** [comment]
Still able to replicate it with
```
dotnet --version
2.1.4

gauge version
Gauge version: 1.0.1.nightly-2018-07-09
Commit Hash: 72109fa

Plugins
-------
dotnet (0.0.2.nightly-2018-07-16)
```

**Comment by BugDiver** [comment]
Seems like `dotnet` generates the debug `obj` (unlinked) as well for `release` config, but no `dll's` are generated. It's the same behavior with a normal `dotnet` app as well.
