### ISSUE TITLE
Alias usage statistics must be available

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-dotnet#16]
**Actual behavior**
Statistics are not available for steps with alias

**Steps to replicate**
* Create an alias step
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using Gauge.CSharp.Lib;
using Gauge.CSharp.Lib.Attribute;

namespace netcore.template
{
    public class Alias
    {
        [Step({"alias1","alias2"})]
        public void HelloWorld(string user_name) {
            // create user user_name
        }
    }
}
```
* The step is not recognized and its usages are not reflected

**Version**
```
Gauge version: 1.0.1.nightly-2018-07-09
Commit Hash: 72109fa

Plugins
-------
dotnet (0.0.2.nightly-2018-07-10)
```
Blocks #6

**Comment by BugDiver** [comment]
@sguptatw The Syntax for aliases is wrong. 
The correct syntax is -
```
 [Step("alias1","alias2")]
public void HelloWorld(string user_name) {
  // create user user_name
}
```

**Comment by sguptatw** [comment]
Followed the syntax given in the documentation - https://docs.gauge.org/latest/writing-specifications.html#step-alias. May be the documentation needs to be addressed.

**Comment by sguptatw** [comment]
Documentation updated to reflect the correct usage.
