### ISSUE TITLE
version 0.4.0 plugin is missing net5.0 binaries

### ISSUE THREAD

**Issue by simmonskeith** [getgauge/gauge-dotnet#160]
On a Windows 10 system, after updating to version 0.4.0 of the plugin which should support net5.0, Gauge was reporting the following:
[ERROR] * You intended to execute a .NET program, but dotnet-bin\net5.0\Gauge.Dotnet.dll does not exist.

After checking the plugin folder, I found only the netcoreapp3.0 binaries.  The launcher.cmd parses the output of my' dotnet --version' command as '5.0.202' and attempts to run the net5.0 version of the Gauge.Dotnet.dll, which doesn't exist.

**Comment by sriv** [comment]
gauge-dotnet 0.4.1 should contain net5.0 binaries. Please check

**Comment by simmonskeith** [comment]
gauge-dotnet 0.4.1 has the net5.0 binaries and works great.  Thanks!
