### ISSUE TITLE
Shutdown LSP call takes about 30 seconds

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-dotnet#19]
**Expected behavior**
Shutdown should be faster

**Steps to replicate**
* Run [LSP tests](https://github.com/getgauge/gauge-lsp-tests)
`gauge run specs --env=dotnet-wd`

**Version**
```
Gauge version: 1.0.1.nightly-2018-07-09
Commit Hash: 72109fa

Plugins
-------
dotnet (0.0.2.nightly-2018-07-16)
```

**Comment by BugDiver** [comment]
Fixed in https://github.com/getgauge/gauge-dotnet/commit/7bbe887021b2f60c289b653f14d004b5d442d8ff
