### ISSUE TITLE
.NET 7.0 Support

### ISSUE THREAD

**Issue by mpekurny** [getgauge/gauge-dotnet#193]
I know .NET 7.0 was just released, but just wanted to know if it will be supported and if so, is there a timeframe when the plugin will be updated?

**Comment by zabil** [comment]
There is no active work on Gauge at the moment. However pull requests to this repo to support .net 7.0 will be reviewed and merged.

**Comment by mpekurny** [comment]
@zabil Can you provide some details on that statement. When you say there is no active work on Gauge, is that just the .NET plugin or all of Gauge? And is this temporary or long term?

**Comment by zabil** [comment]
More details here https://github.com/getgauge/gauge/issues/1732

**Comment by mpekurny** [comment]
@zabil @sriv I made a stab at updating to support .NET 7.0. Please let me know if this is correct?

https://github.com/getgauge/gauge-dotnet/pull/194

**Comment by zabil** [comment]
Thanks this @mpekurny it's holiday season here will take a look at it soon.

**Comment by zabil** [comment]
Thanks for the work on this @mpekurny there is a new release out at
https://github.com/getgauge/gauge-dotnet/releases/tag/v0.5.1
