### ISSUE TITLE
Is there any way to enable syntax highlighting for Gauge scripts in VSCode?

### ISSUE THREAD

**Issue by vgarousi** [getgauge/gauge-dotnet#195]
Is there any way to enable syntax highlighting for Gauge scripts in VSCode?
Like to show comments in grey color, and the stpes (starting with *) in different colors...

![image](https://github.com/getgauge/gauge-dotnet/assets/25739397/d7233269-f703-45ff-9cff-c9580035ab1f)

**Comment by zabil** [comment]
It uses VS code's default markdown syntax highlighting at the moment.
