### ISSUE TITLE
[macOS Sierra] gauge init dotnet fails

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-dotnet#2]
**Expected behavior**
Should be able to initialize a dotnet project

**Actual behavior**
Getting the following error
```
Failed to initialize project. fork/exec launcher.sh: permission denied
```

**OS**
macOS Sierra - Version 10.12.5

**Steps to replicate**
* Install dotnet-sdk-2.1.4-osx-gs-x64.pkg
* `gauge init dotnet`

> The above error occurs

**Version**
```
Gauge version: 0.9.8.nightly-2018-02-02
Commit Hash: bff4f46

Plugins
-------
dotnet (0.0.1.nightly-2018-02-05)
html-report (4.0.4.nightly-2018-01-11)
js (2.1.1.nightly-2018-02-05)
ruby (0.4.3.nightly-2018-02-07)
xml-report (0.2.1.nightly-2017-10-26)
```

Bug on story - https://github.com/getgauge/gauge/issues/607

**Comment by sriv** [comment]
Fix should be in nightly >= 12/02/18
