### ISSUE TITLE
Add a new step implementation in a new file - the step should be shown as implemented

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-dotnet#31]
**Expected behavior**
Add a new step implementation in a new file - the step should be shown as implemented

**Actual behavior**
Add a new step implementation in a new file - the step is shown as unimplemented

**Steps to replicate**
* Create a `gauge-dotnet` project
* Add a new step
* Give the implementation in a new file
* Go back to the spec file
* Close the impl file.
* Go back to the spec file
* The step is shown as unimplemented

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-03
Commit Hash: 62a48e5

Plugins
-------
csharp (0.10.6.nightly-2018-11-28)
dotnet (0.1.1.nightly-2018-11-28)
```

**Comment by sriv** [comment]
works as expected in gauge-vscode, closing.
