### ISSUE TITLE
Language runner processes are not killed even after the IDE is closed

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-dotnet#32]
Expected behavior
When the IDE is closed the runner process must get killed

Actual behavior
Runner processes are not killed even after the IDE is closed

Steps to replicate

Open a gauge-dotnet project in the IDE and work on it
Close it
Repeat this for a few projects. Open the task manager you will see the relevant language runner process still running
Observed with gauge-dotnet

**Version**
```
Gauge version: 1.0.4.nightly-2018-12-03
Commit Hash: 62a48e5

Plugins
-------
dotnet (0.1.1.nightly-2018-11-28)
```

**Comment by sriv** [comment]
closing as stale, feel free to comment if you still see this behaviour
