### ISSUE TITLE
Cannot capture screen shot

### ISSUE THREAD

**Issue by harimadusumilli** [getgauge/gauge-dotnet#33]
Hello Gauge Team,

We have installed the following software along with its plugins. I am using DotNet Core to run a selenium Test. When the Test fails, the screen shot is not captured.

gauge -v
Gauge version: 1.0.0
Commit Hash: 5a99965

Plugins
-------
csharp (0.10.5)
dotnet (0.1.0)
html-report (4.0.6)
java (0.6.9)
screenshot (0.0.1)

[AfterScenario]
public void TearDown() {
GaugeScreenshots.Capture();
Driver.Close();
}

I am using the following namespaces too.
using Gauge.CSharp.Lib;
using Gauge.CSharp.Lib.Attribute;

Screen shot is not captured. The error in the html report is displayed as follows.

Expected string "0JA401" to contain "Fail".
at FluentAssertions.Execution.FallbackTestFramework.Throw(String message)

at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)

at FluentAssertions.Primitives.StringAssertions.Contain(String expected, String because, Object[] becauseArgs)

Can you please let us know if this is a known issue or if there is something else that needs to be done in order to capture the screen shot.

**Comment by sriv** [comment]
Is there a project that I can run and take a look?

You probably need to implement a custom screenshot grabber to capture the screenshot from selenium. Perhaps this example can help :

```
class CustomScreenGrabber : ICustomScreenshotGrabber {

    // Return a screenshot byte array
    public byte[] TakeScreenshot() {
        var driver = DriverFactory.getDriver();
        return ((ITakesScreenshot) driver).GetScreenshot().AsByteArray;
    }
}
```

**Comment by sriv** [comment]
@harimadusumilli - did you get this working?

**Comment by harimadusumilli** [comment]
Hello Srikanth,

Thank you for following up with me. We are still working on it. We will let you know either ways if it worked or did not. Thank you for the prompt follow up.

Regards,
Hari



Sent from Mail for Windows 10

**Comment by nablik** [comment]
I am facing a strange behavior in my side with regards to the screenshot on failure.

gauge --version
Gauge version: 1.0.6
Commit Hash: 2bc49db

Plugins
-------
dotnet (0.1.2)
html-report (4.0.8)
screenshot (0.0.1)
xml-report (0.2.2)

So, locally, works like a charm, But when the same test is run on a VM thru VSTS or azuredevops there are no screenshots. is it because the vm has been used as an agent and the machine is locked or is it bug? I am commenting here because I don't know actually if this should be here or in a separate ticket.

**Comment by zabil** [comment]
The most probable cause is that the tests are running in a headless environment. The default screenshot tool captures the current desktop.

To either capture only the browser page screenshots especially in a headless environment please override the default screenshot behaviour. For more info please read
https://docs.gauge.org/writing-specifications.html?#taking-custom-screenshots
