### ISSUE TITLE
AssemblyLoader System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by MysterL31** [getgauge/gauge-dotnet#39]
Hi, currently facing an issue when executing **gauge run**
![Screenshot_25](https://user-images.githubusercontent.com/25892157/58332730-771d8080-7e01-11e9-9093-cab257987ab0.png)

Are you considering or have a assembly resolver when there are assembly dependent (https://github.com/dotnet/coreclr/issues/18410#issuecomment-396308448)?

**Comment by BugDiver** [comment]
@MysterL31  Thanks a lot for the pointers. We will try and check it the solution given the comment works. We will be looking into this issue soon.

**Comment by sriv** [comment]
should be fixed via #106 and released as part of gauge-dotnet v0.1.6. Closing this, please comment if this is still an issue.
