### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Options, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

### ISSUE THREAD

**Issue by marcosmlpf** [getgauge/gauge-dotnet#4]
When trying to load DLLs from a project using .NET Core Dependency Injection, I'm getting above error.
My guess is that current c-sharp plugin (not dotnet) may be facing issues with Binding Redirects.

**Comment by sriv** [comment]
> My guess is that current c-sharp plugin (not dotnet) may be facing issues with Binding Redirects.

I am not sure I understand completely. the `dotnet` and `csharp` plugins are quite independent (except for the `Gauge.CSharp.Lib` package)

Do you have a sample project for me to test this out?

**Comment by marcosmlpf** [comment]
Hi Sriv, I was able to reproduce the error by trying to add .NET Core assemblies for Dependency Injection, as it adds a reference to DLL I've mentioned on the title.

I was also able to fix the issue, by default .NET Core projects doesn't follow assembly redirects, so it requires an update on csproj files.

I've made local changes to Gauge.Dotnet csproj and made it work by including the following property:

<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>

Should I post a Pull Request with this change?

BTW, are there any plans to have this plugin available to be installed from gauge command line?

**Comment by sriv** [comment]
hi @marcosmlpf , PRs are always welcome. Please go ahead and raise one. 

Also, if you have a simple project that you can share, which can be used to replicate the issue, it would help our QA, @sguptatw .

> BTW, are there any plans to have this plugin available to be installed from gauge command line?

Very soon :) We are currently working on max capacity to get some things going on gauge, but this should follow soon.

**Comment by pp1609** [comment]
Which property we have to set true as i am also facing the same issue even after the NuGet package has been added to project.
Could not load file or assembly 'System.Configuration.ConfigurationManager, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. (C:\Users\e3005457\AppData\Roaming\gauge\plugins\dotnet\0.1.1\bin\Config\machine.config line 3) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Kindly help.

**Comment by sriv** [comment]
I am guessing that @marcosmlpf set `CopyLocal` to `true` in their project.

It would help if there is a sample project that can help us trace a cause. Would you be able to share one @pp1609 ? Thanks.

**Comment by pp1609** [comment]
@sriv will definitely share the project. Can you also please help me identifying that why the error is referring to a file which doesn't exist:
C:\Users\user\AppData\Roaming\gauge\plugins\dotnet\0.1.1\bin\Config\machine.config line 3

I am not seeing any folder named Config in bin directory of dotnet plugin. still the exception is referring to that path.

**Comment by sriv** [comment]
`machine.config` is a machine level configuration file that dotnet framework uses to read configuration values. (see https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/)

In this case, I am guessing that the ConfigurationManager is invoked to read some config value, and the framework is falling back to read the machine config since it could not find a `app.config` in the working directory.

Which makes me think - `System.Configuration.ConfigurationManager` isn't available for dotnet Core AFAIK. Is your project targetting .NET Framework or .NET Core?

**Comment by pp1609** [comment]
My project is targetting .net core(netstandard2.0). Also I have added NuGet package System.Configuration.ConfigurationManager  in my project but still facing issue.

**Comment by marcosmlpf** [comment]
Hello, it's been a while, but as far as I remember, I've added this attribute to Gauge.Dotnet csproj

<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>

**Comment by sriv** [comment]
should be fixed via #106 and released as part of gauge-dotnet v0.1.6. Closing this, please comment if this is still an issue.
