### ISSUE TITLE
Add support for multithreading

### ISSUE THREAD

**Issue by jiabiao** [getgauge/gauge-dotnet#40]
Currently, multithreading feature is only supported by Java language runner/plugin.

Given that gauge dotnet plan to add support for running asynchronous steps (https://github.com/getgauge/gauge-dotnet/issues/30), it would be better if guage dotnet supports  enable_multithreading flag at the same time. Otherwise running asynchronous tasks synchronously makes no sense.

**Comment by BugDiver** [comment]
We did some work (spike) to see how much effort it is to implement `multithreading`. The code is available in the `multithreading` branch.
We will triage the issue and try to push a release with the changes soon.

**Comment by BugDiver** [comment]
Multithreading support is available with version 0.2.0

**Comment by smaik1** [comment]
Best thing that could happen to me this year to have multithreading with gauge-dot-net  :)
Many thank to all the gauge team

It would be better to add the activation of this so important feature in the features delivered in release.

Update the gauge documentation, as it is not noted that this functionality is available with dot-net.

Doc gauge:
------------
Note
Currently, only the Java language runner supports parallel execution of specs by using threads.
------------

**Comment by smaik1** [comment]
> Multithreading support is available with version 0.2.0



> Multithreading support is available with version 0.2.0

Best thing that could happen to me this year to have multithreading with gauge-dot-net :)
A big thanks :)

It would be better to add the activation of this so important feature in the features delivered in release.

Update the gauge documentation, as it is not noted that this functionality is available with dot-net.

Doc gauge:
Note
Currently, only the Java language runner supports parallel execution of specs by using threads.

**Comment by zabil** [comment]
Thanks for pointing this out. The document is now updated via https://github.com/getgauge/docs.gauge.org/commit/d77428f2ed28922e40408a611da800bffc85c596
