### ISSUE TITLE
Could not load file or assembly 'System.Configuration.ConfigurationManager exception while executing code which is refernecing this library

### ISSUE THREAD

**Issue by pp1609** [getgauge/gauge-dotnet#43]
Hi,

While executing specs using Gauge i am getting following exception even after adding the System.Configuration.ConfigurationManager NuGet pacakge in the project. Can anyone please help .

Could not load file or assembly 'System.Configuration.ConfigurationManager, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified. (C:\Users\user\AppData\Roaming\gauge\plugins\dotnet\0.1.1\bin\Config\machine.config line 3) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by sriv** [comment]
related #4
