### ISSUE TITLE
Unable to generate implementation. Error: Error while connecting to runner : rpc error: code = Unknown desc = Exception was thrown by handler.

### ISSUE THREAD

**Issue by manavghaigithub** [getgauge/gauge-dotnet#47]
I am getting error message when performing "Create Step Implementation" from spec file.

Steps to reproduce:
1. Create a new dotnet project
2. Create a new step
3. User gets an error message saying step implementation not found
4. Highlight on the step in spec file and select option "Create Step Implementation"
5. Select existing StepImplementation.cs file
6. Users gets an error
Unable to generate implementation. Error: Error while connecting to runner : rpc error: code = Unknown desc = Exception was thrown by handler.

Version:

VSCode: 1.33.1
Gauge VSCode's Extension - 0.0.10

Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-02-14)
html-report (4.0.7)
java (0.7.2)
screenshot (0.0.1)

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed.
Tested version:
```
Gauge version: 1.0.6.nightly-2019-08-01
Commit Hash: 2bc49db

Plugins
-------
csharp (0.10.5)
dotnet (0.1.2.nightly-2019-08-12)
```

**Comment by Drunknbgfoot** [comment]
I got this same issue today with different reproduction steps.

1. Have working dotnet project
2. use terminal in VS code with command: dotnet add system.windows.forms.dll
3. Type code to use system.windows.forms (sendkeys)
4. Run scenario
5. Test passes with errors, but scenario did not run

Unable to connect to plugin Html Report 4.0.12. rpc error: code = Unavailable desc = error reading from server: read tcp 127.0.0.1:54448->127.0.0.1:54447: wsarecv: An existing connection was forcibly closed by the remote host.

Failed to kill plugin Html Report 4.0.12. TerminateProcess: Access is denied.

Error occurred while waiting for plugin process to finish.
Error : exit status 1
Specifications:	0 executed	0 passed	0 failed	0 skipped
Scenarios:	0 executed	0 passed	0 failed	0 skipped

Total time taken: 24ms
Success: Tests passed.

Gauge version: 1.2.1

Plugins
-------
csharp (0.10.6)
dotnet (0.4.1)
html-report (4.0.12)
java (0.7.15)
js (2.3.17)
screenshot (0.0.1)
xml-report (0.2.3)
