### ISSUE TITLE
Ubuntu CI checks are broken

### ISSUE THREAD

**Issue by Thunderforge** [getgauge/gauge-dotnet#58]
When someone submits a PR to this project, a number of Continuous Integration checks are run, namely

1. tests / Dotnet build (ubuntu-latest)
2. tests / Dotnet build (windows-latest)
3. tests / Dotnet FTs on ubuntu-latest
4. tests / Dotnet FTs on windows-latest
5. tests / Dotnet LSP tests ubuntu-latest
6. tests / Dotnet LSP tests windows-latest
7. verification/cla-signed

Tests number 3 and 5 are broken, as shown with #54 and #55, which only added a `.md` file and thus are not expected to break any tests.

Looking into the run information (e.g. [this one](https://github.com/getgauge/gauge-dotnet/runs/419773197)) shows the root cause is this:

        [Gauge]
        Failed to start gauge API: Timed out connecting to dotnet

With these tests failing, we have no idea if new PRs work properly on Ubuntu. If this could be fixed, we would be obliged.

**Comment by negiDharmendra** [comment]
@Thunderforge this issue should be resolved now. Refer to [this comment ](https://github.com/getgauge/gauge-dotnet/pull/57#issuecomment-587287102) in #57
