### ISSUE TITLE
Parse c# files statically

### ISSUE THREAD

**Issue by BugDiver** [getgauge/gauge-dotnet#7]
Currently, runner scans all the `dlls` when it starts. The `dlls` are loaded even for the `validation` and refactoring.
We should be parsing c# files statically and build the step registry, load the `dlls` only for execution. `Validation`, `Refactoring` and other requests should be processed with the step-registry build with static parsed files.

Parent Issue - #6

**Comment by sguptatw** [comment]
ItemGroup removed in project files should be honoured by LSP is tracked separately https://github.com/getgauge/gauge-dotnet/issues/18
