### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by aerotog** [getgauge/gauge-dotnet#91]
On latest master, a couple tests are failing.

Tests were passing as of 2f4b718f030d586d26a8173874cad8928a5d0a9b 

Upgrading MOQ from 4.13 to 4.14 broke ShouldGetTargetAssembly 
96b73fc07f8445ec40dd4ee07b4cc7349eb81a9f 

Licence change to Apache 2 broke ShouldProcessMessageForExistingClass
bda39f3e80b10915f818ceb8563087b91ed5454b 

It looks like there were no actual code changes. The tests are failing simply because of a file content change (Apache license) and a Moq library behavior change.

I have some free time so hope to open a PR this weekend.

OS: Win 10
gauge-dotnet: 0.1.4

**Comment by sriv** [comment]
hi @aerotog - thanks for bringing this up. 

GH actions reported the checks passed 

- https://github.com/getgauge/gauge-dotnet/runs/687739226?check_suite_focus=true
- https://github.com/getgauge/gauge-dotnet/runs/621723638?check_suite_focus=true

The PRs are merged only when all checks passed. Need to investigate why the errors aren't breaking the builds.

A PR would be most appreciated! Thanks in advance.

**Comment by aerotog** [comment]
The builds may have passed, but the tests failed even then:

> Test Run Failed.
Total tests: 138
     Passed: 137
     Failed: 1

> Test Run Failed.
Total tests: 28
     Passed: 27
     Failed: 1

**Comment by aerotog** [comment]
I've updated the run scripts so the Github actions will catch test failures. You can see the expected build failures in my personal fork [here](https://github.com/aerotog/gauge-dotnet/runs/791378145?check_suite_focus=true).

I'll open a PR once I have the tests passing again.

**Comment by NivedhaSenthil** [comment]
Fixed by 7ef9328
