### ISSUE TITLE
Travis build is failing

### ISSUE THREAD

**Issue by aerotog** [getgauge/gauge-dotnet#92]
The Travis build has been [failing for 8 months](https://travis-ci.org/github/getgauge/gauge-dotnet/builds). It looks like the last run was 7 months ago, so perhaps the Travis builds have been disabled.

The most recent build failed to pull a cert from a URL but the URL does exist.

**Comment by sriv** [comment]
thanks for reporting this. We moved all our builds to github actions, and I see that we've missed updating the README badge. 

You can see newer builds here: https://github.com/getgauge/gauge-dotnet/actions

**Comment by aerotog** [comment]
I'll look into updating the README badge to use GH actions.

**Comment by NivedhaSenthil** [comment]
Closing as the ReadMe is updated
