### ISSUE TITLE
Object cache not cleared according to gauge_clear_state_level

### ISSUE THREAD

**Issue by raweaver** [getgauge/gauge-dotnet#96]
I noticed with Gauge 1.1.1 and dotnet 0.1.4 plugin that Gauge is not clearing the object cache according the setting in `gauge_clear_state_level`.

To reproduce the issue:
1. Create a new directory
2. Create a new gauge project
`using gauge init dotnet`
3. Open folder in Visual Studio Code
4. Confirm `gauge_clear_state_level` is set to `scenario`
5. Add constructor to StepImplementation class to log object creation to console in order to log when gauge instantiates the class.
```
public StepImplementation()
{
    Console.WriteLine("Creating StepImplementation class instance.");
}
```
6. Run the `example.spec` specification.
7. Verify the log only shows the StepImplementation class instantiated once in the first scenario when it should have been instantiated again for the second scenario.
```
Running tool: gauge run c:\_dev\gauge\cache-test\specs\example.spec --simple-console --hide-suggestion
C:\<user-directory>\AppData\Roaming\gauge\plugins\dotnet\0.1.4>dotnet bin\Gauge.Dotnet.dll --start
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
# Specification Heading
  ## Vowel counts in single word
Creating StepImplementation class instance.
  ## Vowel counts in multiple word

Successfully generated html-report to => c:\_dev\gauge\cache-test\reports\html-report\index.html

Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped

Total time taken: 264ms
Success: Tests passed.
```

From what I can tell, the issue is that the ScenarioExecutionEndingProcess and SpecExecutionEndingProcessor classes do not clear the cache using `ClearCacheForConfiguredLevel()`.

Each class currently implements:
```
public ExecutionStatusResponse Process(SpecExecutionEndingRequest request)
{
    _executionOrchestrator.CloseExecutionScope();
    return ExecuteHooks(request.CurrentExecutionInfo);
}
```

It appears it should implement this?
```
public ExecutionStatusResponse Process(SpecExecutionEndingRequest request)
{
    _executionOrchestrator.CloseExecutionScope();
    var result = ExecuteHooks(request.CurrentExecutionInfo);
    ClearCacheForConfiguredLevel();
    return result;
}
```

I was able to observe the expected behavior with a local build of the dotnet plugin using the above changes.
```
Running tool: gauge run c:\_dev\gauge\cache-test\specs\example.spec --simple-console --hide-suggestion
C:\<user-directory>\AppData\Roaming\gauge\plugins\dotnet\0.1.4>dotnet bin\Gauge.Dotnet.dll --start
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
# Specification Heading
  ## Vowel counts in single word
Creating StepImplementation class instance.
  ## Vowel counts in multiple word
Creating StepImplementation class instance.

Successfully generated html-report to => c:\_dev\gauge\cache-test\reports\html-report\index.html

Specifications:	1 executed	1 passed	0 failed	0 skipped
Scenarios:	2 executed	2 passed	0 failed	0 skipped

Total time taken: 301ms
Success: Tests passed.
```

Any help would be greatly appreciated!
Thank you!

**Comment by BugDiver** [comment]
@raweaver Thanks for reporting the issue and the detailed explanation. 

Since you have already figured the possible solution, would you like to submit a PR? We would be happy to discuss/merge it.
